#!/bin/python3

import os


#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    # Write your code here
    principal = 0
    secondary = 0
    n = len(arr)
    for i in range(0, n):  
        for j in range(0, n):  
  
            # Condition for principal diagonal 
            if (i == j): 
                principal += arr[i][j] 
  
            # Condition for secondary diagonal 
            if ((i + j) == (n - 1)): 
                secondary += arr[i][j]
    return (abs(principal - secondary))
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
